version: "3.9"
services:
    frontend:
        build: frontend
        ports:
            - 3000:8090
    backend:
        build: backend
        environment:
            MONGO_CONNECTION: "mongodb://mongodb/chat-app-db"
        ports:
            - 5000:5000
    mongodb:
        image: mongo
        ports:
            - 37017:27017
        volumes:
            - ./data:/data/db
