version: "3.9"
services:
    frontend:
        build: frontend
        ports:
            - 80:80
            - 443:443
        environment:
            VAR_BASE_URL: "http://localhost"
            GENERATE_SOURCEMAP: false
        links:
            - "backend"
    backend:
        build: backend
        environment:
            MONGO_CONNECTION: ""
        ports:
            - 5000:5000
            - 3005:3005
