version: "3.9"
services:
    frontend:
        build: frontend
        ports:
            - 80:80
            - 443:443
        environment:
            REACT_APP_BASE_URL: "http://localhost"
            GENERATE_SOURCEMAP: false
        links:
            - "backend"
    backend:
        build: backend
        environment:
            MONGO_CONNECTION: ""
            REDIS_CONNECTION: "redis://default@redis:6379"
        ports:
            - 5000:5000
            - 3005:3005
        depends_on:
            - redis
            # - mongodb

    # mongodb:
    #     image: mongo
    #     ports:
    #         - 37017:27017
    #     volumes:
    #         - ./data:/data/db
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    # environment:
    #     - ALLOW_EMPTY_PASSWORD=yes
    #     - REDIS_PASSWORD=123
